#!/bin/bash
set -euxo pipefail

echo "Running track setup script on host docker-vm"

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Install pulumi
apt -y update
apt -y install git
curl -fsSL https://get.pulumi.com | sh
export PATH=/root/.pulumi/bin:$PATH

# install latest node
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

apt -y update
apt -y install docker-compose-plugin gcc g++ make vim nano nodejs
