##############################################################################
# Instruqt Github Actions Workflow
#
# This workflow will generate the track-slugs.yml file
#
##############################################################################
name: generate

env:
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  TRACK_DIR: instruqt-tracks
  
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

jobs:
  CreateTrackSlugs:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create track-slugs.yml
        run: chmod +x ./.github/scripts/generate-slugs.sh; ./.github/scripts/generate-slugs.sh

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generating track-slugs.yml file