#!/bin/bash
set -euxo pipefail

if [ ! -f /newrelic/apps/login-service/.env ]; then
    fail-message "Couldn't find a .env file in apps/login-service. Did you run make?"
    exit 1
fi

if [ ! -f /newrelic/apps/web-api/.env ]; then
    fail-message "Couldn't find a .env file in apps/web-api. Did you run make?"
    exit 1
fi

if ! docker image ls | grep "api"; then
    fail-message "Couldn't find the api image. Did you run docker compose up?"
    exit 1
fi

if ! docker image ls | grep "login"; then
    fail-message "Couldn't find the login image. Did you run docker compose up?"
    exit 1
fi