#!/bin/bash
set -euxo pipefail

echo "Running challenge setup script on host docker-vm"

# Initialize the home directory with the Dockerfile
mkdir /newrelic
set-workdir /newrelic
git clone https://github.com/ptahdunbar/o11y-as-code-pulumi-newrelic /newrelic